spring.application.name=json-platform

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.admin.email=${ADMIN_EMAIL:adminadprob9@json.com}
app.admin.password=${ADMIN_PASSWORD:admin123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true